### ISSUE TITLE
Show ISC options for the Featured Image block in WordPress 5.9

### ISSUE THREAD

**Issue by webzunft** [image-source-control/image-source-control#137]
We already show the ISC options for the image block in the editor in the backend.
WordPress 5.9 comes with a new "Post Featured Image" block, which should also show these fields.

![Bildschirmfoto 2022-01-18 um 10 12 27](https://user-images.githubusercontent.com/2728720/149906450-be63f40c-38c9-4aaf-bc9a-9182021a8919.png)

Priority
---

Higher, since WordPress 5.9 is around the corner.

**Comment by cnhk** [comment]
@webzunft There is a bit of unexpected problem with this one.

This block is "linked" to the post featured image (the one you set from the edit page/post sidebar). If you set an image for this block, the usual post featured image is also set.

The problem is that, for some reason, this block does not accept any string attributes (the type we use for the image source , the image source etc.). It only accepts numbers, Boolean and object.

It is likely the final behavior (not 100% sure), so to add the ISC fields on this new block we have to use an object attributes which makes things more complicated.

So, do we still add the fields right now? Or maybe wait for 5.9 to be released and see if there is any solution other than using object attribute.

**Comment by webzunft** [comment]
> So, do we still add the fields right now? Or maybe wait for 5.9 to be released and see if there is any solution other than using object attribute.

Thanks! Let’s wait then.

**Comment by cnhk** [comment]
@webzunft @Galanos  The new block accepts all kind of attributes. I might have misinterpreted something back then, or there were some bugs.

Just one note though, the featured media ID is the one the last time the post was saved. (https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/#getcurrentpost).

It means that if you set a featured image and then try to edit the block before saving the post the field is not shown. Even worse, if you already have a featured image then change it to another image, the ISC fields is the ones from the old image until you save the post.

May be worth adding a small warning when the the featured image is changed? (didn't researched yet how to detect that but it shouldn't be too complicated). For now the feature is ready for testing.

**Comment by Galanos** [comment]
@cnhk I haven’t thought about it yet—will this issue affect the new (for WP 6.0) feature _“Use the Featured Image in a Cover block”,_ too, or will we have to treat that separately? I describe this new feature in relation to unrelated display problems in #176.

> It means that if you set a featured image and then try to edit the block before saving the post the field is not shown.

Do you mean that the whole ISC accordion element won’t be shown in the sidebar for that block?

> Even worse, if you already have a featured image then change it to another image, the ISC fields is the ones from the old image until you save the post.

I reckon that if the user were to modify the ISC fields at this point (before saving), he would do so for the old image?

**Comment by Galanos** [comment]
Update with info from Slack talks:
- the “Use the Featured Image in a Cover block” feature is to be treated separately
- we have found a way to avoid the ID problem described above; review is ongoing
