### ISSUE TITLE
Featured image source link is not visible due to color

### ISSUE THREAD

**Issue by webzunft** [image-source-control/image-source-control#193]
When the featured image source is displayed below the excerpt on archive pages, it might not be visible on a white background.

The reason is, that it uses the same class as the overlay: `isc-source-text`, which recently got the color white to be better visible on the dark overlay background.

![white-source-link](https://user-images.githubusercontent.com/2728720/172450745-3e20bee4-cc4c-48d7-adc1-ed230f45803d.gif)

Expected behavior
---

The link on archive pages should use a default theme color.

Priority
---

Mid. No one complained yet, but it decreases reliability.

Additional context
---

The source string used here receives the `isc-source-text` class, though it is not an overlay. I think we can safely remove or change it.

**Comment by webzunft** [comment]
Some questions I got after testing different ideas:

- Changing `isc-source-text` into something else might break manual changes that users did before. This should be clear from the changelog, but even then is not great.
- Adding another class, e.g., `isc-source-text isc-featured-image-source-text` would allow us to customize the CSS rule that makes the link on overlays white. It looks complicated then.
- Do we want the source links to look like the default theme’s link color? Or would we rather have a pre-defined color applied globally. I am voting for the default color, which was the option before, but just wanted to ask the question anyway.

**Comment by Galanos** [comment]
I think that the implications of assigning the `isc-source-text` class to this link aren’t what we had in mind and what the user would expect. I can’t see any reason to style both the Overlay and the “Source-Below-Excerpts” identically. One is block-like, the other is inline-like.

How about we rewrite the selector for the recently re-styled **Overlay** class to include its (reliably known) parent elements? Then, I reckon, the “Source-Below-Excerpts” would stop responding to it and fall back to its initial styling. Which would probably be the theme’s styling, since there wouldn’t exist any selectors by ISC targeting it. What do you think?

**Comment by webzunft** [comment]
I fear that there is no reliable parent element to the overlay. It is generally following an image. But could also follow a link tag – with the image inside that link. It would definitely also need more than one selector / rule to target without being 100% sure if other setups will be affected.
I think changing the class of the inline source could have the least unexpected effects.

**Comment by webzunft** [comment]
Good catch. I changed my PR accordingly.
